name: update_directory_md
on: [push, pull_request]
jobs:
  update_directory_md:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Run tests for validation script
        run: ruby -rminitest/autorun scripts/validate_filepaths.rb
      - name: validate filepaths
        run: ruby scripts/validate_filepaths.rb
